### PR TITLE
Handle builtins appropriately for resolve 1.11.0. Fixes #394.

### LINKED ISSUE #394: Adding exports to CJS modules with built-in names broken by resolve 1.11.1
Resolve changed how it resolves built-in module specifiers like `buffer` (this also [impacted rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve/pull/223)). The impact is you can no longer add exports for e.g. `assert` like the following:

```js
  cjs({
    namedExports: {
      assert: ["deepEqual"]
    }
  });
```

This plugin starts by building a map from resolved module path to declared named exports for that module. The resolve change means the keys for built-in modules went from a resolved path to the like-named npm module to simply returning the built-in name back.

I see three potential fixes here:

1. similar to https://github.com/rollup/rollup-plugin-node-resolve/pull/223, we do a two-pass resolution, first attempting to resolve with "/" appended, and falling back if we can't find anything.
2. if adding named exports for node builtins isn't a thing, we append "/" to any specifier that's a built-in module.
3. update the documentation to be clear that "buffer" and "buffer/" are two different things, and you should be intentional about which you are declaring named exports for. This would also enable a person to provide different named exports for a built-in and an npm package with the same name. I'm not sure if this is valuable.

Do the maintainers have any thoughts on the best fix here?

### PR DESCRIPTION
**Pull request by bterlson**
See relevant discussion in #394.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -16,10 +16,19 @@ export default function commonjs(options = {}) {
...
+			let resolveId = id;
 			let resolvedId;
 
+			if (isCore(id)) {
+				// resolve will not find npm modules with the same name as
+				// core modules without a trailing slash. Since core modules
+				// must be external, we can assume any core modules defined
+				// here are npm modules by that name.
+				resolveId += '/';
+			}
```
Comment (lukastaegert) [inline src/index.js]: 👍
