### PR TITLE
Prepare for 1.0.0, fix some issues

### LINKED ISSUE #341: Build halts prematurely with no error for incorrectly configured build
Here's a [repro repo](https://github.com/skeggse/rollup-cjs-repro). Run `npm run broken` to see the broken behavior, and `npm run working` for the behavior when we have the correct config.

We have two modules `a` and `b`. `a` is a `commonjs` module. `a` uses functionality exposed by `b`. `a` resolves `b` using some other plugin (i.e. not by a relative `require`). `a` is included in the `commonjs.include` config, but `b` is not. `b` can be a `commonjs` module _or_ an es native module.

Expected behavior: we get an error.

Actual behavior: no error, exit code `0`.

This is super distilled from the original problem I had, which also involved `rollup-plugin-node-resolve` and `rollup-plugin-alias`, but this seems to be exclusively a problem with the `commonjs` plugin.

### LINKED ISSUE #348: Default re-export does not get unwrapped
I've got a [repro repo](https://github.com/skeggse/rollup-cjs-default-repro) for this issue. Run `npm run broken` to see the broken behavior, and `npm run working` for the behavior with a workaround (using what seems to be equivalent constructs).

Unexpected behavior:

```js
// Using
export {name as default} from 'lib';

// Unexpected output
function name() {}

var libWorking = /*#__PURE__*/Object.freeze({
        default: name
});

var lib = ( libWorking && thing ) || libWorking;

// lib is the default export available to the commonjs module
```

Expected behavior:

```js
// Using
import {name} from 'lib';
export default name;

// Expected output
function name() {}

var libBroken = /*#__PURE__*/Object.freeze({
        default: name
});

// libBroken is the default export available to the commonjs module
```

I expect commonjs modules that `require` other modules to have access to the default export. Moreover, the behavior isn't consistent, so while my expectation might be wrong, I still see the behavior I want with a slight change in the re-export construct.

I was also seeing some strange behavior caused by supplying a `cache` object to rollup - it would fix the broken behavior on rebuild. I haven't been able to isolate a repro case yet, though.

### PR DESCRIPTION
**Pull request by lukastaegert**
Besides making the tests ready for rollup@1.0.0 (the production code was already working), this will also fix two issues:
* resolves #348 by extending the default export detection logic to search for both `export default ...` as well as `export {... as default}`.
* resolves #341 by properly setting the CJS promise for filtered and otherwise ignored files

Furthermore, it prevents a `default is not exported` warning by putting the ESM import wrapper into a function which is not optimized by rollup. Lastly, importing ESM with known default exports will produce more optimized code.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -74,40 +75,42 @@ export default function commonjs(options = {}) {
...
 						return `import { __moduleExports } from ${JSON.stringify(
 							actualId
 						)}; export default __moduleExports;`;
-					else if (esModulesWithoutDefaultExport.indexOf(actualId) !== -1)
+					else if (esModulesWithoutDefaultExport[actualId])
 						return `import * as ${name} from ${JSON.stringify(actualId)}; export default ${name};`;
+					else if (esModulesWithDefaultExport[actualId]) {
+						return `export {default} from ${JSON.stringify(actualId)};`;
+					}
 					else
```
Comment (guybedford) [inline src/index.js]: What's the logic for modules that neither don't have a default nor have a default?

**Comment by lukastaegert** [comment]
> Most of this is about `require('x.mjs')` cases right? And dealing with the `export default x` handling to work out ergonomically?

Yes exactly. In case there is a known default export, the generated code will be much shorter.

There are still quite a few cases where the deoptimized wrapper is used. I have an idea how this could be solved while making the CJS detection much more straightforward at the same time. This would require a new plugin context function, e.g. `fetchModule`, which would allow the transform function to trigger loading, transforming and parsing a module the same way Rollup would (or just return the result if this has already happened) and return the AST (if the result is stored by Rollup, each module would still be fetched and transformed only once). If this is done for *every* import in a CJS file, we can decide for all but the external imports whether they have a default and produce much better code. But this is just an idea for now which would require quite a bit of work on Rollup's side.
